version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: ./express-app
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    env_file:
      - ./express-app/.env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    env_file:
      - ./react-app/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
