apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
        - name: express-app
          image: elitron/car-rental-backend
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017/carrentaldb"
            - name: PORT
              value: "3000"
            - name: JWT_SECRET
              value: "_"
            - name: GOOGLE_CLIENT_ID
              value: "_"
            - name: CARXE_API_KEY
              value: "_"
            - name: SMTP_HOST
              value: "_"
            - name: SMTP_PORT
              value: "_"
            - name: SMTP_SECURE
              value: "_"
            - name: SMTP_USER
              value: "_"
            - name: SMTP_PASS
              value: "_"
            - name: SMTP_FROM
              value: "_"
            - name: STRIPE_SECRET_KEY
              value: "_"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
