name: Build & Deploy to Minikube
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # 1. Get the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Build your Express backend image
      - name: Build backend image
        shell: powershell
        run: |
          docker build --no-cache -t elitron/car-rental-backend ./express-app

      # 3. Build your React frontend image
      - name: Build frontend image
        shell: powershell
        run: |
          docker build --no-cache -t elitron/car-rental-frontend ./react-app

      # 4. Log in to Docker Hub securely
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # 5. Push both images up to your Docker Hub repo
      - name: Push backend image
        shell: powershell
        run: docker push elitron/car-rental-backend

      - name: Push frontend image
        shell: powershell
        run: docker push elitron/car-rental-frontend

      # 6. Deploy MongoDB manifests
      - name: Deploy MongoDB
        shell: powershell
        run: |
          kubectl apply -f mongo-deployment.yaml -n car-rental
          kubectl apply -f mongo-service.yaml -n car-rental

      # 7. Deploy the Express backend
      - name: Deploy Express backend
        shell: powershell
        run: |
          kubectl apply -f express-app/deployment.yaml -n car-rental
          kubectl apply -f express-app/service.yaml -n car-rental

      # 8. Deploy the React frontend
      - name: Deploy React frontend
        shell: powershell
        run: |
          kubectl apply -f react-app/deployment.yaml -n car-rental
          kubectl apply -f react-app/service.yaml -n car-rental
