name: Build & Deploy to Minikube
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [self-hosted, Windows, X64]

    steps:
      # 1. Get the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Ensure Docker is running with elevated privileges
      - name: Start Docker Service
        run: |
          Start-Service docker
        shell: powershell

      # 3. Build your Express backend image
      - name: Build backend image
        run: |
          docker build \
            --no-cache \
            -t elitron/car-rental-backend \
            ./express-app
        shell: bash

      # 4. Build your React frontend image
      - name: Build frontend image
        run: |
          docker build \
            --no-cache \
            -t elitron/car-rental-frontend \
            ./react-app
        shell: bash

      # 5. Log in to Docker Hub securely
      - name: Docker Hub login
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        shell: bash

      # 6. Push both images up to your Docker Hub repo
      - name: Push backend image
        run: docker push elitron/car-rental-backend

      - name: Push frontend image
        run: docker push elitron/car-rental-frontend

      # 7. Deploy MongoDB manifests
      - name: Deploy MongoDB
        run: |
          kubectl apply -f mongo-deployment.yaml -n car-rental
          kubectl apply -f mongo-service.yaml -n car-rental
        shell: bash

      # 8. Deploy the Express backend
      - name: Deploy Express backend
        run: |
          kubectl apply -f express-app/deployment.yaml -n car-rental
          kubectl apply -f express-app/service.yaml -n car-rental
        shell: bash

      # 9. Deploy the React frontend
      - name: Deploy React frontend
        run: |
          kubectl apply -f react-app/deployment.yaml -n car-rental
          kubectl apply -f react-app/service.yaml -n car-rental
        shell: bash
